CSUN-SeniorDesign/sandbox-worms-blog

- content/article/team-setup-domain-name.md
This is to try pull request workflow. 
I only made minor edit.
please review and approve
> trial pull request

- content/article/marksblogweek2.md
- content/article/marksblogweek2backup.md
> my post for the week

- content/article/Mark-Github-Help.md
When you can please do this request.
> addind a help file for git

- content/article/johnblog3.md
> john week 3 blog

- content/article/terraforming-AWS.md
> 3rdweekblogpost

- content/article/nickblog3.md
please review and merge at earliest convenience, thanks!
> week 3 blog

- content/article/week4playbook.md
> aubrey week4 post

- content/article/marksblogweek4.md
Someone please approve and merge my blog post.
> marks4thblog

- .circleci/config.yml
- content/article/circleofdevops.md
Features:
- Build a container with hugo. specific version selected
- install aws cli
- put a filter so it doesnt run on PR
- runhugo
- tarball the file and named it shaofthecommit.tar.gz
- copy to s3
> Project2 - CircleCI config.yml

- .circleci/config.yml
put a filter on hold so it doesnt run on master
> Project2 staging

- content/article/circleofdevops.md
> aubrey week5 blog

- content/article/marksblogweek5.md
> marksBlog5

- content/article/marksblogweek6.md
Want to merge my blog for week 6
> addMarksBlogWk6

- content/article/marksblogweek6.md
> addMarksBlogWk6again

- content/article/johnblog7.md
> John blog 7

- content/article/marksblogweek7.md
> marksblog7

- content/article/marksblogweek8.md
pull for adding a blog and then trying to remove it
> marksblog8test

- content/article/marksblogweek8.md
> Marks blog week 8

- content/article/johnblog9.md
> Project4 - John Blog 9

- content/article/marksblogweek16.md
- content/article/marksblogweek17.md
> marksblog17

- content/article/marksblogweek20.md
> markblog20
